# Permalinks
permalink:           pretty

# Setup
title:               Nkosilathi Tauro
tagline:             Software Developer Cape Town, RSA.
url:                 http://nkosi-tauro.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nkosilathi Tauro
  url:               https://linkedin.com/in/nkosi-tauro
  email:             nkosilati23@gmail.com

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/nkosi-tauro/nkosi-tauro.github.io
linkedin:             nkosi-tauro
github:              nkosi-tauro


# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
